# Essential terminal tools for this dotfiles setup
# Run: brew bundle install --file=~/.dotfiles/Brewfile
brew 'colordiff'
brew 'diffutils'
brew 'gnupg'
brew 'go'
brew 'gopls'
brew 'grpcurl'
brew 'htop'
brew 'jq'
brew 'neovim'
brew 'node'
brew 'python'
brew 'pyright'
brew 'ripgrep'
brew 'tig'
brew 'tmux'
brew 'vim'
brew 'virtualenv'
brew 'wget'
brew 'yq'
brew 'zsh-autosuggestions'
brew 'zsh-completions'
brew 'zsh-syntax-highlighting'
